{% set name = "urdfdom" %}
{% set version = "1.0.3" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://github.com/ros/{{ name }}/archive/{{ version }}.tar.gz
  sha256: 839d939fbd91d115f928a6e02334638829c58d9c8ea2f81bfa3faffd233c154c
  patches:
    - cmake.patch
    - windows-install.patch

build:
  number: 1
  skip: true  # [win and vc<14]
  run_exports:
    - urdfdom

requirements:
  build:
    - {{ compiler('cxx') }}
    - cmake
    - make  # [unix]
  host:
    - console_bridge
    - tinyxml
    - urdfdom_headers
  run:
    - console_bridge
    - tinyxml
    - urdfdom_headers

test:
  requires:
    - pkg-config  # [unix]
  commands:
    - pkg-config --modversion {{ name }}  # [unix]
    - test -f $PREFIX/lib/lib{{ name }}_model${SHLIB_EXT}  # [unix]
    - if exist %PREFIX%\\Library\\CMake\\urdfdom-config.cmake (exit 0) else (exit 1)  # [win]

about:
  home: http://github.com/ros/urdfdom
  license: BSD-3-Clause
  license_family: BSD
  license_file: LICENSE
  summary: 'URDF parser'
  dev_url: https://github.com/ros/urdfdom

extra:
  recipe-maintainers:
    - jcarpent
    - wolfv
    - lesteve
